#!/bin/bash
set -e

P2P_PORT=9876
HTTP_PORT=800
CONFIG=nodes/data/config/config.ini.producer
KEY="signature-provider = EOS8TzVdLNnNWYWKXaKRFC5k8DA3851Mgk7jfhxXWib6N5YXfTCyb=KEY:5KXyCh714JSskkLerjGRmBaSYPvKVHazsEJfbC9bdcmrAdipEiV"
PRODUCER_NAME=produceracc
HTTP_SERVER="http-server-address = 0.0.0.0:"
P2P_ENDPOINT="p2p-listen-endpoint = 0.0.0.0:"
P2P_PEER="p2p-peer-address ="
DOCKER_COMPOSE=docker-compose.yml

function setup_producers() {

  echo -ne "\nSeting up config.ini files..."

  for i in `seq 1 $producers`
  do
      cp $CONFIG "$CONFIG$i"
      echo "#***GENERATED BY CONFIG SCRIPT***" >> "$CONFIG$i"
      for j in `seq 1 $producers`
      do
        if [ $i -ne $j ]
        then
          echo "$P2P_PEER producer$j:$P2P_PORT" >> "$CONFIG$i"
        fi
      done
      echo "producer-name = $PRODUCER_NAME$i" >> "$CONFIG$i"
      echo $KEY >> "$CONFIG$i"
      echo "#PRODUCERS" >> "$CONFIG$i"

  done

  echo -e "OK\n"
}

function create_compose() {
  echo -ne "\nCreating docker-compose file..."


  if test -f "$DOCKER_COMPOSE"; then
      rm $DOCKER_COMPOSE
  fi

  cp template-docker-compose.yml  $DOCKER_COMPOSE

  if [ $producers -eq 0 ]
  then
    echo -e "OK\n"
    start_docker
  fi

  echo "#***GENERATED BY CONFIG SCRIPT***" >> docker-compose.yml

  for i in `seq 1 $producers`
  do
    echo "  producer$i:" >> docker-compose.yml
    echo "    container_name: producer$i-node" >> docker-compose.yml
    echo "    depends_on:" >> docker-compose.yml
    echo "      - genesis" >> docker-compose.yml
    echo "    image: producer" >> docker-compose.yml
    echo "    ports:" >> docker-compose.yml
    echo "      - '$HTTP_PORT$i:8888'" >> docker-compose.yml
    echo "    volumes:" >> docker-compose.yml
    echo "      - ./nodes/data/config/config.ini.producer$i:/opt/producer/config.ini" >> docker-compose.yml
    echo "      - ./nodes/data/config/genesis.json:/opt/producer/genesis.json" >> docker-compose.yml
  done

  echo -e "OK\n"

}

function start_docker() {
  echo -e "Starting containers...\n"

  #docker-compose build

  docker-compose up -d

  echo -e "Booting up the network...\n"

  docker exec -ti genesis-node ./bootup.sh $producers

  docker-compose logs -f

}

#args parser
if [ $# -eq 0 ]
then
  echo "Usage: ./startup.sh {PRODUCERS}"
elif [ $1 -eq 0 ]
then
  producers=$1
  create_compose
  start_docker
else
  producers=$1
  setup_producers
  create_compose
  start_docker
fi
